/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdatvedelemRouteImport } from './routes/adatvedelem'
import { Route as EdzesekRouteImport } from './routes/edzesek'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdatvedelemRoute = AdatvedelemRouteImport.update({
  id: '/adatvedelem',
  path: '/adatvedelem',
  getParentRoute: () => rootRouteImport,
} as any)
const EdzesekRoute = EdzesekRouteImport.update({
  id: '/edzesek',
  path: '/edzesek',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adatvedelem': typeof AdatvedelemRoute
  '/edzesek': typeof EdzesekRoute
  '/kapcsolat': typeof KapcsolatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adatvedelem': typeof AdatvedelemRoute
  '/edzesek': typeof EdzesekRoute
  '/kapcsolat': typeof KapcsolatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adatvedelem': typeof AdatvedelemRoute
  '/edzesek': typeof EdzesekRoute
  '/kapcsolat': typeof KapcsolatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adatvedelem' | '/edzesek' | '/kapcsolat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adatvedelem' | '/edzesek' | '/kapcsolat'
  id: '__root__' | '/' | '/adatvedelem' | '/edzesek' | '/kapcsolat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdatvedelemRoute: typeof AdatvedelemRoute
  EdzesekRoute: typeof EdzesekRoute
  KapcsolatRoute: typeof KapcsolatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adatvedelem': {
      id: '/adatvedelem'
      path: '/adatvedelem'
      fullPath: '/adatvedelem'
      preLoaderRoute: typeof AdatvedelemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edzesek': {
      id: '/edzesek'
      path: '/edzesek'
      fullPath: '/edzesek'
      preLoaderRoute: typeof EdzesekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdatvedelemRoute: AdatvedelemRoute,
  EdzesekRoute: EdzesekRoute,
  KapcsolatRoute: KapcsolatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
